# Generated by Django 2.2.5 on 2019-09-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcolormodel',
            name='color',
            field=models.IntegerField(choices=[(1, 'Red'), (2, 'Blue'), (3, 'Green')], default=3),
        ),
    ]
