# Generated by Django 3.0.5 on 2020-05-14 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAccessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_status', models.IntegerField(choices=[(3, 'label_acccess_public'), (2, 'label_acccess_protected'), (1, 'label_acccess_private')], default=3, verbose_name='label_access_status')),
                ('name', models.CharField(default='hello', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestColorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hello', max_length=100)),
                ('color', models.IntegerField(choices=[(1, 'Red'), (2, 'Blue'), (3, 'Green')], default=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestLanguageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=2, verbose_name='label_language')),
                ('name', models.CharField(default='hello', max_length=100)),
            ],
            options={
                'db_table': 'core_tests_testlanguagemodel',
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hello', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_status', models.IntegerField(choices=[(3, 'label_acccess_public'), (2, 'label_acccess_protected'), (1, 'label_acccess_private')], default=3, verbose_name='label_access_status')),
                ('slug', models.SlugField(max_length=255, verbose_name='label_slug')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='label_date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='label_date_updated')),
                ('name', models.CharField(max_length=255, verbose_name='label_name')),
                ('description', models.TextField(blank=True, verbose_name='label_description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coretest_testprojectmodel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'label_project',
                'verbose_name_plural': 'label_project_plural',
                'abstract': False,
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TestTimestampModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='label_date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='label_date_updated')),
                ('name', models.CharField(default='hello', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestTrackedFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hello', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestUUIDModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='hello', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestUserstampModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hello', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coretest_testuserstampmodel_created_objects', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coretest_testuserstampmodel_last_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestTranslationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=2, verbose_name='label_language')),
                ('name', models.CharField(default='hello', max_length=100)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coretest_testtranslationmodel_children', to='coretest.TestTranslationModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestProjectPublishMemberModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='label_date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='label_date_updated')),
                ('role', models.IntegerField(choices=[(3, 'label_role_admin'), (2, 'label_role_editor'), (1, 'label_role_author')], default=1, verbose_name='label_role')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coretest_testprojectpublishmembermodel', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_publish_members', to='coretest.TestProjectModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestProjectContentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hello', max_length=100)),
                ('content', models.TextField(verbose_name='content')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coretest_testprojectcontentmodel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestParentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hello', max_length=100)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coretest_testparentmodel_children', to='coretest.TestParentModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestProjectMemberModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='label_date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='label_date_updated')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coretest_testprojectmembermodel', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='coretest.TestProjectModel')),
            ],
            options={
                'verbose_name': 'label_project_member',
                'verbose_name_plural': 'label_project_member_plural',
                'abstract': False,
                'unique_together': {('member', 'project')},
            },
        ),
        migrations.CreateModel(
            name='TestOrderedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('name', models.CharField(default='hello', max_length=100)),
                ('foo_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foo_items', to='coretest.TestModel')),
            ],
            options={
                'index_together': {('foo_group', 'order')},
            },
        ),
    ]
