# Generated by Django 3.0.5 on 2020-05-14 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='label_name')),
                ('description', models.TextField(blank=True, verbose_name='label_description')),
            ],
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_status', models.IntegerField(choices=[(2, 'label_status_published'), (1, 'label_status_draft')], default=1, verbose_name='label_publish_status')),
                ('order', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255, verbose_name='label_name')),
                ('description', models.TextField(blank=True, verbose_name='label_description')),
                ('foo_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foos', to='foo.FooGroup')),
            ],
            options={
                'index_together': {('foo_group', 'order')},
            },
        ),
    ]
