# Generated by Django 3.0.5 on 2020-05-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_status', models.IntegerField(choices=[(2, 'label_status_published'), (1, 'label_status_draft')], default=1, verbose_name='label_publish_status')),
                ('name', models.CharField(max_length=255, verbose_name='label_name')),
                ('description', models.TextField(blank=True, verbose_name='label_description')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
